services:
  web:
    build: .
    environment:
      HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000